import React, { useState } from "react";
import ArtCard from "../components/ArtCard";
import styles from "./Home.module.css";
import { connectWallet, disconnectWallet } from "../util/wallet";
import { useWallet } from "../hooks/useWallet";

const Home: React.FC = () => {
  const { address, isPending } = useWallet();
  const buttonLabel = isPending ? "Loading..." : "Connect";
  const [displayModal, setDisplayModal] = useState(false);
  const AppName = "Stellar Squares";

  return (
    <div className={styles.pageWrapper}>
      <header>
        <h1 className={styles.titleHeader}>Stellar Squares</h1>
        <button
          className={styles.textButton}
          onClick={() => setDisplayModal(true)}
        >
          What's this?
        </button>
        <div
          className={displayModal ? styles.infoModal : styles.infoModalHidden}
        >
          <p>
            A generative art collection featuring geometric squares in the style
            of Georg Nees' Schotter. Each piece is a unique NFT generated by a
            unique run of a program, showcasing the beauty of controlled
            randomness and minimalist design.
          </p>

          <p>
            Connect your wallet to purchase one from the gallery, before they're
            all sold.
          </p>
          <button
            className={styles.textButton}
            onClick={() => setDisplayModal(false)}
          >
            Hide collection info
          </button>
        </div>
      </header>
      <nav className={styles.navigation}>
        {!address && (
          <button
            className={styles.navButton}
            onClick={() => void connectWallet()}
            disabled={isPending}
          >
            {buttonLabel}
          </button>
        )}
        {address && (
          <>
            <div className={styles.activeAddress}>{address}</div>
            <button
              className={styles.navButton}
              onClick={() => {
                void disconnectWallet();
              }}
            >
              Disconnect
            </button>
          </>
        )}
      </nav>
      <main>
        <div className={styles.artCardsGrid}>
          {Array.from(Array(20)).map((_, tokenId) => (
            <ArtCard key={`card-${tokenId}`} tokenId={tokenId} />
          ))}
        </div>
      </main>
      <footer>
        <span>
          © {new Date().getFullYear()} {AppName}. Licensed under the{" "}
          <a
            href="http://www.apache.org/licenses/LICENSE-2.0"
            target="_blank"
            rel="noopener noreferrer"
          >
            Apache License, Version 2.0
          </a>
          .
        </span>
      </footer>
    </div>
  );
};

export default Home;
